//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reductor {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExamplesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExamplesResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reductor.ExamplesResource", typeof(ExamplesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Reductor&gt;
        ///  &lt;InputData MaximumInletPressure=&quot;35000000&quot; MinimumInletPressure=&quot;7830000&quot; OutletPressure=&quot;5220000&quot; InitialInletTemperature=&quot;293&quot; Consumption=&quot;1&quot; /&gt;
        ///  &lt;ReductorType ValveStroke=&quot;Reverse&quot; Balansed=&quot;No&quot; BarSpringAvaliable=&quot;No&quot; /&gt;
        ///  &lt;ReductorParameters&gt;
        ///    &lt;ValveParameters ValveDiameter=&quot;0,0094&quot; ValveSaddleWidth=&quot;0,0003&quot; /&gt;
        ///    &lt;PistonParameters LowPressurePistonDiameter=&quot;0,05&quot; /&gt;
        ///    &lt;MainSpringParameters Draw=&quot;12416&quot; Resiliency=&quot;500000&quot; Index=&quot;3&quot; CoilDiameter=&quot;0,014307&quot; CoilCount=&quot;10,399&quot;  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Редуктор_обратного_хода_неуравновешенный_без_запорной_пружины {
            get {
                return ResourceManager.GetString("Редуктор_обратного_хода_неуравновешенный_без_запорной_пружины", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Reductor&gt;
        ///  &lt;InputData MaximumInletPressure=&quot;35000000&quot; MinimumInletPressure=&quot;7830000&quot; OutletPressure=&quot;5220000&quot; InitialInletTemperature=&quot;293&quot; Consumption=&quot;1&quot; /&gt;
        ///  &lt;ReductorType ValveStroke=&quot;Reverse&quot; Balansed=&quot;No&quot; BarSpringAvaliable=&quot;Yes&quot; /&gt;
        ///  &lt;ReductorParameters&gt;
        ///    &lt;ValveParameters ValveDiameter=&quot;0,0094&quot; ValveSaddleWidth=&quot;0,0003&quot; /&gt;
        ///    &lt;PistonParameters LowPressurePistonDiameter=&quot;0,05&quot; /&gt;
        ///    &lt;BarSpringParameters Draw=&quot;189&quot; Resiliency=&quot;8000&quot; Index=&quot;8&quot; CoilDiameter=&quot;0,002496&quot; CoilCount=&quot;5,979&quot; Pitch [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Редуктор_обратного_хода_неуравновешенный_с_запорной_пружиной {
            get {
                return ResourceManager.GetString("Редуктор_обратного_хода_неуравновешенный_с_запорной_пружиной", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Reductor&gt;
        ///  &lt;InputData MaximumInletPressure=&quot;35000000&quot; MinimumInletPressure=&quot;7830000&quot; OutletPressure=&quot;5220000&quot; InitialInletTemperature=&quot;293&quot; Consumption=&quot;1&quot; /&gt;
        ///  &lt;ReductorType ValveStroke=&quot;Reverse&quot; Balansed=&quot;Yes&quot; BarSpringAvaliable=&quot;No&quot; /&gt;
        ///  &lt;ReductorParameters&gt;
        ///    &lt;ValveParameters ValveDiameter=&quot;0,0095&quot; ValveSaddleWidth=&quot;0,0003&quot; /&gt;
        ///    &lt;PistonParameters HighPressurePistonDiameter=&quot;0,0075&quot; LowPressurePistonDiameter=&quot;0,05&quot; /&gt;
        ///    &lt;MainSpringParameters Draw=&quot;11145&quot; Resiliency=&quot;380000&quot; Index=&quot;3,5&quot; Coil [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Редуктор_обратного_хода_уравновешенный_без_запорной_пружины {
            get {
                return ResourceManager.GetString("Редуктор_обратного_хода_уравновешенный_без_запорной_пружины", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Reductor&gt;
        ///  &lt;InputData MaximumInletPressure=&quot;35000000&quot; MinimumInletPressure=&quot;7830000&quot; OutletPressure=&quot;5220000&quot; InitialInletTemperature=&quot;293&quot; Consumption=&quot;1&quot; /&gt;
        ///  &lt;ReductorType ValveStroke=&quot;Reverse&quot; Balansed=&quot;Yes&quot; BarSpringAvaliable=&quot;Yes&quot; /&gt;
        ///  &lt;ReductorParameters&gt;
        ///    &lt;ValveParameters ValveDiameter=&quot;0,0095&quot; ValveSaddleWidth=&quot;0,0003&quot; /&gt;
        ///    &lt;PistonParameters HighPressurePistonDiameter=&quot;0,0075&quot; LowPressurePistonDiameter=&quot;0,05&quot; /&gt;
        ///    &lt;BarSpringParameters Draw=&quot;184&quot; Resiliency=&quot;20000&quot; Index=&quot;3,5&quot; CoilDia [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Редуктор_обратного_хода_уравновешенный_с_запорной_пружиной {
            get {
                return ResourceManager.GetString("Редуктор_обратного_хода_уравновешенный_с_запорной_пружиной", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Reductor&gt;
        ///  &lt;InputData MaximumInletPressure=&quot;35000000&quot; MinimumInletPressure=&quot;7830000&quot; OutletPressure=&quot;5220000&quot; InitialInletTemperature=&quot;293&quot; Consumption=&quot;1&quot; /&gt;
        ///  &lt;ReductorType ValveStroke=&quot;Straight&quot; Balansed=&quot;No&quot; BarSpringAvaliable=&quot;Yes&quot; /&gt;
        ///  &lt;ReductorParameters&gt;
        ///    &lt;ValveParameters ValveDiameter=&quot;0,019&quot; ValveSaddleWidth=&quot;0,0003&quot; /&gt;
        ///    &lt;PistonParameters HighPressurePistonDiameter=&quot;0,0191&quot; /&gt;
        ///    &lt;BarSpringParameters Draw=&quot;0&quot; Resiliency=&quot;5000&quot; Index=&quot;3&quot; CoilDiameter=&quot;0&quot; CoilCount=&quot;0&quot; Pitch=&quot;0&quot; Diame [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Редуктор_прямого_хода_с_двумя_полостями_c_запорной_пружиной {
            get {
                return ResourceManager.GetString("Редуктор_прямого_хода_с_двумя_полостями_c_запорной_пружиной", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Reductor&gt;
        ///  &lt;InputData MaximumInletPressure=&quot;35000000&quot; MinimumInletPressure=&quot;7830000&quot; OutletPressure=&quot;5220000&quot; InitialInletTemperature=&quot;293&quot; Consumption=&quot;1&quot; /&gt;
        ///  &lt;ReductorType ValveStroke=&quot;Straight&quot; Balansed=&quot;No&quot; BarSpringAvaliable=&quot;No&quot; /&gt;
        ///  &lt;ReductorParameters&gt;
        ///    &lt;ValveParameters ValveDiameter=&quot;0,019&quot; ValveSaddleWidth=&quot;0,0003&quot; /&gt;
        ///    &lt;PistonParameters HighPressurePistonDiameter=&quot;0,0191&quot; /&gt;
        ///    &lt;MainSpringParameters Draw=&quot;1600&quot; Resiliency=&quot;100000&quot; Index=&quot;3,45&quot; CoilDiameter=&quot;0,005339&quot; CoilCount=&quot;12, [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Редуктор_прямого_хода_с_двумя_полостями_без_запорной_пружины {
            get {
                return ResourceManager.GetString("Редуктор_прямого_хода_с_двумя_полостями_без_запорной_пружины", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Reductor&gt;
        ///  &lt;InputData MaximumInletPressure=&quot;35000000&quot; MinimumInletPressure=&quot;7830000&quot; OutletPressure=&quot;5220000&quot; InitialInletTemperature=&quot;293&quot; Consumption=&quot;1&quot; /&gt;
        ///  &lt;ReductorType ValveStroke=&quot;Straight&quot; Balansed=&quot;Yes&quot; BarSpringAvaliable=&quot;Yes&quot; /&gt;
        ///  &lt;ReductorParameters&gt;
        ///    &lt;ValveParameters ValveDiameter=&quot;0,013&quot; ValveSaddleWidth=&quot;0,0003&quot; /&gt;
        ///    &lt;PistonParameters HighPressurePistonDiameter=&quot;0,01335&quot; LowPressurePistonDiameter=&quot;0,019&quot; /&gt;
        ///    &lt;BarSpringParameters Draw=&quot;0&quot; Resiliency=&quot;5000&quot; Index=&quot;3&quot; CoilDiamet [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Редуктор_прямого_хода_с_четырьмя_полостями_c_запорной_пружиной {
            get {
                return ResourceManager.GetString("Редуктор_прямого_хода_с_четырьмя_полостями_c_запорной_пружиной", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Reductor&gt;
        ///  &lt;InputData MaximumInletPressure=&quot;35000000&quot; MinimumInletPressure=&quot;7830000&quot; OutletPressure=&quot;5220000&quot; InitialInletTemperature=&quot;293&quot; Consumption=&quot;1&quot; /&gt;
        ///  &lt;ReductorType ValveStroke=&quot;Straight&quot; Balansed=&quot;Yes&quot; BarSpringAvaliable=&quot;No&quot; /&gt;
        ///  &lt;ReductorParameters&gt;
        ///    &lt;ValveParameters ValveDiameter=&quot;0,013&quot; ValveSaddleWidth=&quot;0,0003&quot; /&gt;
        ///    &lt;PistonParameters HighPressurePistonDiameter=&quot;0,01335&quot; LowPressurePistonDiameter=&quot;0,019&quot; /&gt;
        ///    &lt;MainSpringParameters Draw=&quot;1726&quot; Resiliency=&quot;160000&quot; Index=&quot;3,4&quot; Coi [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Редуктор_прямого_хода_с_четырьмя_полостями_без_запорной_пружины {
            get {
                return ResourceManager.GetString("Редуктор_прямого_хода_с_четырьмя_полостями_без_запорной_пружины", resourceCulture);
            }
        }
    }
}
